In [235]:
import pandas as pd
import numpy as np

In [236]:
from sklearn.metrics.pairwise import cosine_similarity

In [237]:
data = pd.read_csv("ALL LAWYERS - Sheet1.csv")

In [238]:
data.head()

S.NO Enrollment number                          Name Specialization  \
0     1     Ms. 2701/2015                S. R. Iyalpari    Arbitration   
1     2     Ms. 2701/2015                S. R. Iyalpari          Civil   
2     3     Ms. 2701/2015                S. R. Iyalpari        Divorce   
3     4     Ms. 2701/2015                S. R. Iyalpari         Family   
4     5      MS/3485/2017  Sathya Narayanan Subramanian          Civil   

   Experience    Location Success rate  Avg .Rating  
0           8  Coimbatore          85%          4.1  
1           8  Coimbatore          85%          4.1  
2           8  Coimbatore          85%          4.1  
3           8  Coimbatore          85%          4.1  
4           6  Coimbatore          89%          4.9

In [239]:
data.shape

(76, 8)

In [240]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   S.NO               76 non-null     int64  
 1   Enrollment number  76 non-null     object 
 2   Name               76 non-null     object 
 3   Specialization     76 non-null     object 
 4   Experience         76 non-null     int64  
 5   Location           76 non-null     object 
 6   Success rate       76 non-null     object 
 7   Avg .Rating        76 non-null     float64
dtypes: float64(1), int64(2), object(5)
memory usage: 4.9+ KB


In [241]:
data.describe()

S.NO  Experience  Avg .Rating
count  76.000000   76.000000    76.000000
mean   37.973684   15.644737     4.481579
std    21.649926    9.591251     0.417520
min     1.000000    3.000000     3.900000
25%    19.750000    8.000000     4.100000
50%    37.500000   14.000000     4.700000
75%    56.250000   23.000000     4.900000
max    75.000000   40.000000     5.000000

In [242]:
data['Location'].unique()

array(['Coimbatore', 'Erode', 'Trichy', 'Dindigul', 'Chennai', 'chennai'],
      dtype=object)

In [243]:
data['Location'].replace('chennai','Chennai',inplace=True)

In [244]:
data['Location'].unique()

array(['Coimbatore', 'Erode', 'Trichy', 'Dindigul', 'Chennai'],
      dtype=object)

In [245]:
data.isnull().sum()

S.NO                 0
Enrollment number    0
Name                 0
Specialization       0
Experience           0
Location             0
Success rate         0
Avg .Rating          0
dtype: int64

In [246]:
data['Enrollment number'].unique()

array(['Ms. 2701/2015', 'MS/3485/2017', 'MS/826/2017', '--',
       'MS/2575/2007', 'MS/2912/2010', 'MS/1715/1999', 'MS/2842/2009',
       'MS/1222/1996', 'MS/1060/2000', 'MS/2240/2014', 'MS/226/2009',
       'MS/2114/2011', 'MS/1162/1991', 'MS/2517/2008', 'MS/852/2008',
       'MS/77/1997', 'MS/2347/2008', 'TN/527/2005', 'Ms/1812/1999',
       'MS/133/1985', 'MS 1982/2009', 'MS/813/2016', 'TN/1040/2002',
       'MS/430/2009', 'MS.311/1983'], dtype=object)

In [247]:
data['Enrollment number'].replace('--','NA',inplace=True)

In [248]:
data['Enrollment number'].unique()

array(['Ms. 2701/2015', 'MS/3485/2017', 'MS/826/2017', 'NA',
       'MS/2575/2007', 'MS/2912/2010', 'MS/1715/1999', 'MS/2842/2009',
       'MS/1222/1996', 'MS/1060/2000', 'MS/2240/2014', 'MS/226/2009',
       'MS/2114/2011', 'MS/1162/1991', 'MS/2517/2008', 'MS/852/2008',
       'MS/77/1997', 'MS/2347/2008', 'TN/527/2005', 'Ms/1812/1999',
       'MS/133/1985', 'MS 1982/2009', 'MS/813/2016', 'TN/1040/2002',
       'MS/430/2009', 'MS.311/1983'], dtype=object)

In [249]:
data['Name'].value_counts()

S. R. Iyalpari                  4
Shankar Ganesh Rajendran        4
Adhithyan C                     4
Balajanaki Srinivasan           4
Preethi A                       3
Gayathri                        3
Rajesh Kannan                   3
R. Edwin Jayakumar              3
A. Gobikannan                   3
A Sahul Hameed                  3
P. Vijay Akilan                 3
G Jayaprakash                   3
Dhanagodi                       3
Thangavel Krishnan              3
M. Dheenadhayalan               3
Kavitha D                       3
Abarajithan R                   2
Sathya Narayanan Subramanian    2
A.R. Poorvaja                   2
D Parthibhan                    2
S. Bhavani                      2
Sakthivel                       2
S. Saranraj                     2
Ravi Shankar                    1
Raghuraman Balaji               1
Suresh Kumar                    1
Rama S                          1
B Elan Kumaran                  1
Vijaya                          1
Sarvana Kumar 

In [250]:
print("Total No.of Lawyers Unique: ", len(data['Name'].unique()))

Total No.of Lawyers Unique:  33


In [251]:
data

S.NO Enrollment number                          Name  Specialization  \
0      1     Ms. 2701/2015                S. R. Iyalpari     Arbitration   
1      2     Ms. 2701/2015                S. R. Iyalpari           Civil   
2      3     Ms. 2701/2015                S. R. Iyalpari         Divorce   
3      4     Ms. 2701/2015                S. R. Iyalpari          Family   
4      5      MS/3485/2017  Sathya Narayanan Subramanian           Civil   
..   ...               ...                           ...             ...   
71    71       MS/813/2016                  D Parthibhan           Civil   
72    72      TN/1040/2002                  Ravi Shankar     Arbitration   
73    73                NA             Raghuraman Balaji  Consumer Court   
74    74       MS/430/2009                  Suresh Kumar        Criminal   
75    75       MS.311/1983             S. Thenkodi Annam        Criminal   

    Experience    Location Success rate  Avg .Rating  
0            8  Coimbatore          85%          4.1  
1            8  Coimbatore          85%          4.1  
2            8  Coimbatore          85%          4.1  
3            8  Coimbatore          85%          4.1  
4            6  Coimbatore          89%          4.9  
..         ...         ...          ...          ...  
71           7     Chennai          90%          4.7  
72          21     Chennai          90%          4.7  
73           7     Chennai          80%          4.0  
74          14     Chennai          81%          4.0  
75          40     Chennai          82%          4.0  

[76 rows x 8 columns]

In [252]:
data['Success rate'] = data['Success rate'].str.rstrip('%').astype(int)

In [253]:
data.head(3)

S.NO Enrollment number            Name Specialization  Experience  \
0     1     Ms. 2701/2015  S. R. Iyalpari    Arbitration           8   
1     2     Ms. 2701/2015  S. R. Iyalpari          Civil           8   
2     3     Ms. 2701/2015  S. R. Iyalpari        Divorce           8   

     Location  Success rate  Avg .Rating  
0  Coimbatore            85          4.1  
1  Coimbatore            85          4.1  
2  Coimbatore            85          4.1

In [254]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   S.NO               76 non-null     int64  
 1   Enrollment number  76 non-null     object 
 2   Name               76 non-null     object 
 3   Specialization     76 non-null     object 
 4   Experience         76 non-null     int64  
 5   Location           76 non-null     object 
 6   Success rate       76 non-null     int32  
 7   Avg .Rating        76 non-null     float64
dtypes: float64(1), int32(1), int64(2), object(4)
memory usage: 4.6+ KB


In [255]:
lawyer_data = data.copy()
lawyer_data

S.NO Enrollment number                          Name  Specialization  \
0      1     Ms. 2701/2015                S. R. Iyalpari     Arbitration   
1      2     Ms. 2701/2015                S. R. Iyalpari           Civil   
2      3     Ms. 2701/2015                S. R. Iyalpari         Divorce   
3      4     Ms. 2701/2015                S. R. Iyalpari          Family   
4      5      MS/3485/2017  Sathya Narayanan Subramanian           Civil   
..   ...               ...                           ...             ...   
71    71       MS/813/2016                  D Parthibhan           Civil   
72    72      TN/1040/2002                  Ravi Shankar     Arbitration   
73    73                NA             Raghuraman Balaji  Consumer Court   
74    74       MS/430/2009                  Suresh Kumar        Criminal   
75    75       MS.311/1983             S. Thenkodi Annam        Criminal   

    Experience    Location  Success rate  Avg .Rating  
0            8  Coimbatore            85          4.1  
1            8  Coimbatore            85          4.1  
2            8  Coimbatore            85          4.1  
3            8  Coimbatore            85          4.1  
4            6  Coimbatore            89          4.9  
..         ...         ...           ...          ...  
71           7     Chennai            90          4.7  
72          21     Chennai            90          4.7  
73           7     Chennai            80          4.0  
74          14     Chennai            81          4.0  
75          40     Chennai            82          4.0  

[76 rows x 8 columns]

In [256]:
data['Specialization'].replace({'Arbitration':0,
                                'Civil':1,
                                'Consumer Court':2,
                                'Criminal':3,
                                'Divorce':4,
                                'Family':5}, inplace=True)

In [257]:
data['Specialization'].unique()

array([0, 1, 4, 5, 3, 2], dtype=int64)

In [258]:
data['Location'].replace({'Chennai':0,
                          'Coimbatore':1,
                          'Dindigul':2,
                          'Erode':3,
                          'Trichy':4}, inplace=True)

In [259]:
data['Location'].unique()

array([1, 3, 4, 2, 0], dtype=int64)

In [260]:
data.head()

S.NO Enrollment number                          Name  Specialization  \
0     1     Ms. 2701/2015                S. R. Iyalpari               0   
1     2     Ms. 2701/2015                S. R. Iyalpari               1   
2     3     Ms. 2701/2015                S. R. Iyalpari               4   
3     4     Ms. 2701/2015                S. R. Iyalpari               5   
4     5      MS/3485/2017  Sathya Narayanan Subramanian               1   

   Experience  Location  Success rate  Avg .Rating  
0           8         1            85          4.1  
1           8         1            85          4.1  
2           8         1            85          4.1  
3           8         1            85          4.1  
4           6         1            89          4.9

In [261]:
features = ['Specialization', 'Experience', 'Location', 'Success rate', 'Avg .Rating']
X = data[features].values

In [262]:
similarity_matrix = cosine_similarity(X, X)

In [263]:
similarity_matrix

array([[1.        , 0.99993158, 0.99890693, ..., 0.99959931, 0.99629009,
        0.93545372],
       [0.99993158, 1.        , 0.99938538, ..., 0.99982179, 0.99664805,
        0.93577379],
       [0.99890693, 0.99938538, 1.        , ..., 0.99966901, 0.99690387,
        0.93596591],
       ...,
       [0.99959931, 0.99982179, 0.99966901, ..., 1.        , 0.99642925,
        0.93371623],
       [0.99629009, 0.99664805, 0.99690387, ..., 0.99642925, 1.        ,
        0.96042163],
       [0.93545372, 0.93577379, 0.93596591, ..., 0.93371623, 0.96042163,
        1.        ]])

In [273]:
def get_user_input():
    user_specialization = int(input('Select Specialization:\n0.Arbitration\n1.Civil\n2.Consumer Court\n3.Criminal\n4.Divorce\n5.Family\n'))
    user_experience = int(input('Enter Experience (in years) : '))
    user_location = int(input('Select Location:\n0.Chennai\n1.Coimbatore\n2.Dindigul\n3.Erode\n4.Trichy\n'))
    user_success_rate = int(input('Enter the % of Success Rate [Eg: 85, 90] : '))
    user_avg_rating = float(input('Enter the Average Rating [out of 5] : '))
    
    user_requirements = [user_specialization, user_experience, user_location, user_success_rate, user_avg_rating]
    return user_requirements

In [292]:
user_requirements = get_user_input()

Select Specialization:
0.Arbitration
1.Civil
2.Consumer Court
3.Criminal
4.Divorce
5.Family
2
Enter Experience (in years) : 10
Select Location:
0.Chennai
1.Coimbatore
2.Dindigul
3.Erode
4.Trichy
1
Enter the % of Success Rate [Eg: 85, 90] : 89
Enter the Average Rating [out of 5] : 4


In [293]:
user_requirements

[2, 10, 1, 89, 4.0]

In [294]:
user_similarity = cosine_similarity([user_requirements], X).flatten()

In [295]:
user_similarity

array([0.99958304, 0.99977553, 0.9995329 , 0.9991797 , 0.99889538,
       0.99839417, 0.99893878, 0.99894575, 0.99874375, 0.9990062 ,
       0.99717733, 0.99722281, 0.99643137, 0.99684931, 0.99937862,
       0.9994297 , 0.99871489, 0.99918242, 0.99909739, 0.99941795,
       0.99745788, 0.99752372, 0.99694652, 0.98850264, 0.99919877,
       0.98890102, 0.98908192, 0.98895766, 0.99702431, 0.99767883,
       0.99773316, 0.99758015, 0.99762743, 0.99694552, 0.97854348,
       0.98327957, 0.98369232, 0.97803805, 0.97792562, 0.97792562,
       0.99925134, 0.99921385, 0.99720059, 0.99703756, 0.99663637,
       0.9973432 , 0.99924289, 0.99907878, 0.99922527, 0.97703054,
       0.97697372, 0.97691396, 0.99817978, 0.99801872, 0.99774397,
       0.99826031, 0.99812963, 0.99786296, 0.97836309, 0.99816183,
       0.99833729, 0.99516668, 0.99496363, 0.98500776, 0.96088452,
       0.96113857, 0.96112051, 0.9610059 , 0.99896086, 0.99895203,
       0.99926627, 0.99926185, 0.99281121, 0.99961935, 0.99808

In [296]:
# Rank lawyers based on similarity
ranked_lawyers = pd.Series(user_similarity, index=data.index).sort_values(ascending=False)
ranked_lawyers

1     0.999776
73    0.999619
0     0.999583
2     0.999533
15    0.999430
        ...   
65    0.961139
66    0.961121
67    0.961006
64    0.960885
75    0.942146
Length: 76, dtype: float64

In [307]:
ranked_lawyer_dataset = data.loc[ranked_lawyers.index]

In [298]:
ranked_lawyer_dataset

S.NO Enrollment number                   Name  Specialization  Experience  \
1      2     Ms. 2701/2015         S. R. Iyalpari               1           8   
73    73                NA      Raghuraman Balaji               2           7   
0      1     Ms. 2701/2015         S. R. Iyalpari               0           8   
2      3     Ms. 2701/2015         S. R. Iyalpari               4           8   
15    16                NA              Kavitha D               2          12   
..   ...               ...                    ...             ...         ...   
65    65       MS/133/1985  Balajanaki Srinivasan               2          38   
66    66       MS/133/1985  Balajanaki Srinivasan               3          38   
67    67       MS/133/1985  Balajanaki Srinivasan               4          38   
64    64       MS/133/1985  Balajanaki Srinivasan               0          38   
75    75       MS.311/1983      S. Thenkodi Annam               3          40   

    Location  Success rate  Avg .Rating  
1          1            85          4.1  
73         0            80          4.0  
0          1            85          4.1  
2          1            85          4.1  
15         1            82          4.1  
..       ...           ...          ...  
65         0            92          4.9  
66         0            92          4.9  
67         0            92          4.9  
64         0            92          4.9  
75         0            82          4.0  

[76 rows x 8 columns]

In [299]:
filtered_lawyers = ranked_lawyer_dataset[(ranked_lawyer_dataset['Specialization'] == user_requirements[0]) & (ranked_lawyer_dataset['Location'] == user_requirements[2])]

In [300]:
filtered_lawyers

S.NO Enrollment number                       Name  Specialization  \
15    16                NA                  Kavitha D               2   
9     10       MS/826/2017  Shankar Ganesh Rajendran                2   
21    22      MS/2575/2007          M. Dheenadhayalan               2   
11    12                NA                Adhithyan C               2   

    Experience  Location  Success rate  Avg .Rating  
15          12         1            82          4.1  
9            6         1            88          4.7  
21          16         1            87          4.7  
11           3         1            80          4.0

In [301]:
top_lawyers_data = lawyer_data.loc[filtered_lawyers.index]
top_lawyers_data

S.NO Enrollment number                       Name  Specialization  \
15    16                NA                  Kavitha D  Consumer Court   
9     10       MS/826/2017  Shankar Ganesh Rajendran   Consumer Court   
21    22      MS/2575/2007          M. Dheenadhayalan  Consumer Court   
11    12                NA                Adhithyan C  Consumer Court   

    Experience    Location  Success rate  Avg .Rating  
15          12  Coimbatore            82          4.1  
9            6  Coimbatore            88          4.7  
21          16  Coimbatore            87          4.7  
11           3  Coimbatore            80          4.0

In [319]:
sorted_lawyers = top_lawyers_data.sort_values(by=['Experience', 'Success rate', 'Avg .Rating'], ascending=[False, False, False])
sorted_lawyers

S.NO Enrollment number                       Name  Specialization  \
21    22      MS/2575/2007          M. Dheenadhayalan  Consumer Court   
15    16                NA                  Kavitha D  Consumer Court   
9     10       MS/826/2017  Shankar Ganesh Rajendran   Consumer Court   
11    12                NA                Adhithyan C  Consumer Court   

    Experience    Location  Success rate  Avg .Rating  
21          16  Coimbatore            87          4.7  
15          12  Coimbatore            82          4.1  
9            6  Coimbatore            88          4.7  
11           3  Coimbatore            80          4.0

In [320]:
sorted_lawyers = sorted_lawyers.reset_index(drop=True)
sorted_lawyers.index = sorted_lawyers.index+1
sorted_lawyers.drop(columns=['S.NO'])

Enrollment number                       Name  Specialization  Experience  \
1      MS/2575/2007          M. Dheenadhayalan  Consumer Court          16   
2                NA                  Kavitha D  Consumer Court          12   
3       MS/826/2017  Shankar Ganesh Rajendran   Consumer Court           6   
4                NA                Adhithyan C  Consumer Court           3   

     Location  Success rate  Avg .Rating  
1  Coimbatore            87          4.7  
2  Coimbatore            82          4.1  
3  Coimbatore            88          4.7  
4  Coimbatore            80          4.0